--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.4.7.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 08/08/2025 21:36:52
-- Server version: 12.0.2000.8
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'31b5f06d-716f-40d4-806e-a19e795e3d97', 'Mendillorri', '31016', 'España', 'Pamplona', 0, '2025-08-08 11:24:30.717', '2025-08-08 11:24:30.717')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'3243256a-5e4f-46ab-8efe-ab9566a023ef', 'Azpilagaña', '31006', 'España', 'Pamplona', 0, '2025-08-08 10:56:40.837', '2025-08-08 10:56:40.837')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'50642a92-4605-414f-bc6f-2f4446853ea0', 'Etxabakoitz', '31010', 'España', 'Pamplona', 0, '2025-08-08 11:57:33.003', '2025-08-08 11:57:33.003')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'681339a7-63c8-4da9-9b20-b861f5014a84', 'Ermitagaña', '31008', 'España', 'Pamplona', 0, '2025-08-08 11:01:45.330', '2025-08-08 11:01:45.330')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'6e658731-76b1-4cfe-b664-c7ad8d2fba20', 'Cuenca Pamplona', '31009', 'España', 'Pamplona', 0, '2025-08-08 11:09:10.333', '2025-08-08 11:09:10.333')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'7514fd61-8795-4176-9124-487129e36cb0', 'Segundo Ensanche', '31003', 'España', 'Pamplona', 0, '2025-08-08 11:21:05.910', '2025-08-08 11:21:05.910')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'7d6b0b4a-867c-4fe2-ad32-a3e7875bf94a', 'Casco Viejo', '31001', 'España', 'Pamplona', 0, '2025-08-08 10:58:56.290', '2025-08-08 10:58:56.290')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'86a913c5-b71c-455c-9cd0-94772fc8ce10', 'Rochapea', '31014', 'España', 'Pamplona', 0, '2025-08-08 11:22:33.937', '2025-08-08 11:22:33.937')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'936baa5a-81e1-4f29-b1e9-de3fb4560fd8', 'Iturrama', '31007', 'España', 'Pamplona', 0, '2025-08-08 10:50:09.143', '2025-08-08 10:50:09.143')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'b578d7b9-77b5-418d-b4c8-99687be5b7e4', 'Txantrea', '31015', 'España', 'Pamplona', 0, '2025-08-08 10:59:33.900', '2025-08-08 10:59:33.900')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'c7896312-4e65-4d02-b304-afd69724de26', 'San Juan', '31011', 'España', 'Pamplona', 0, '2025-08-08 11:56:41.120', '2025-08-08 11:56:41.120')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'd32e6bf6-a23d-4260-b44e-8e478d8239e3', 'Primer Ensanche', '31002', 'España', 'Pamplona', 0, '2025-08-08 11:20:39.327', '2025-08-08 11:20:39.327')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'da41c669-1209-415e-a6d2-d175d6d0bf27', 'Milagrosa', '31005', 'España', 'Pamplona', 0, '2025-08-08 11:23:09.943', '2025-08-08 11:23:09.943')
INSERT devdemobbdd.dbo.District(Id, Name, Zipcode, Country, City, BuildingCount, CreatedAt, UpdatedAt) VALUES (N'e9e18c08-eeb9-435b-a366-f4b1bf7b5241', 'Buztintxuri', '31012', 'España', 'Pamplona', 0, '2025-08-08 10:57:52.910', '2025-08-08 10:57:52.910')
GO