--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.4.7.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 08/08/2025 21:37:02
-- Server version: 12.0.2000.8
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
